# Generated by Django 4.0.2 on 2022-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='matricule',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
